name: Fetch and preprocess some feeds
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt install p7zip-full wget
    - name: Fetch and preprocess Dubai
      run: |-
        cd scripts && ./dubai.sh
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated Bot"
        git config user.email "info@interline.io"
        git add -A
        timestamp=$(date -u)
        git commit -m "Feed(s) fetched and preprocessed" || exit 0
        git push
