name: Fetch GRTC
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt install libgbm1
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: GRTC
      run: |-
        cd scripts
        npm install puppeteer
        node grtc.js
      env:
        GRTC_USERNAME: ${{ secrets.GRTC_USERNAME }}
        GRTC_PASSWORD: ${{ secrets.GRTC_PASSWORD }}
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated Bot"
        git config user.email "info@interline.io"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest version of GRTC" || exit 0
        git push
