name: Fetch and preprocess some feeds
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Dubai: 7z and wget
    # GRTC: libgbm1 for Puppeteer
    - name: Install dependencies
      run: |
        sudo apt install p7zip-full wget libgbm1
    - name: Fetch and preprocess Dubai
      run: |-
        cd scripts && ./dubai.sh
    # GRTC
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: GRTC
      run: |-
        cd scripts
        npm install puppeteer
        node grtc.js
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated Bot"
        git config user.email "info@interline.io"
        git add -A
        timestamp=$(date -u)
        git commit -m "Feed(s) fetched and preprocessed" || exit 0
        git push
